ES 5.2.2 Support
tripadvisor/elasticsearch-analysis-korean pull request #5
Opened 2017-03-27 22:12 UTC by adrianocrestani

- I dropped guava dependency. Added Memoizer class to replace depency on guava's Suppliers.memoize()
- bumped analyzer version from 2 to 3
- adapted AnalysisKoreanPlugin to the new ES Plugin API

2017-03-28 12:14 UTC, jpdaigle requested changes
* Looks like the plugin init changed: what's our test plan for making sure this still loads and runs OK?

* If this is bumping the plugin's major version, do we want to keep this on a separate branch? Or better yet, branch off the ES-2.3 version to a maintenance branch and 5.2.2 goes to trunk?

2017-03-28 12:14 UTC, jpdaigle commented on src/main/java/org/apache/lucene/analysis/kr/utils/DictionaryUtil.java
> +    private static Supplier<Map<String, String>> PREFIXS = Memoizer.memoize(() -> readDict(KoreanEnv.FILE_PREFIX));
If this isn't part of the public API (it's private) we should fix spelling: `PREFIXES`

2017-03-28 12:14 UTC, jpdaigle commented on src/main/java/org/apache/lucene/analysis/kr/utils/DictionaryUtil.java
> +    private static Supplier<Map<String, String>> SUFFIXS = Memoizer.memoize(() -> readDict(KoreanEnv.FILE_SUFFIX));
`SUFFIXES`

2017-03-28 12:14 UTC, jpdaigle commented on src/main/java/org/apache/lucene/analysis/kr/utils/DictionaryUtil.java
> +		try {
This whole file reading thing is ugly and could be easily done in "vanilla" Java, but I know you just changed indentation and it's not your bug. 😐

2017-03-28 12:14 UTC, jpdaigle commented on src/main/java/org/apache/lucene/analysis/kr/utils/Memoizer.java
> +        AtomicReference<T> value = new AtomicReference<>();
could be final

2017-03-28 14:20 UTC, adrianocrestani commented on src/main/java/org/apache/lucene/analysis/kr/utils/Memoizer.java
> +        AtomicReference<T> value = new AtomicReference<>();
value or Memoizer class? Anyway, I will make both final

2017-03-28 14:22 UTC, adrianocrestani commented
> Looks like the plugin init changed: what's our test plan for making sure this still loads and runs OK?

@jpdaigle , I have re-run the same tests I described [here](https://github.com/tripadvisor/elasticsearch-analysis-korean/pull/4) to make sure initialization still works.

>  Or better yet, branch off the ES-2.3 version to a maintenance branch and 5.2.2 goes to trunk?

That is exactly what I did :)

2017-03-29 20:07 UTC, jpdaigle commented on src/main/java/Test.java
> +public class Test {
Name isn't very descriptive.

2017-03-29 20:08 UTC, jpdaigle approved these changes

2017-03-29 20:09 UTC, adrianocrestani commented on src/main/java/Test.java
> +public class Test {
oh no, I shouldn't have committed that. I will revert it.

2017-03-29 20:13 UTC, merged

2017-03-30 01:50 UTC, jpdaigle commented
:shipit: